# Generated by Django 4.2.2 on 2023-10-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentInfo",
            fields=[
                (
                    "Tnumber",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("LastName", models.CharField(max_length=50)),
                ("FirstName", models.CharField(max_length=50)),
                ("Email", models.EmailField(max_length=254)),
                ("Classification", models.CharField(max_length=50)),
                ("Graduation_date", models.CharField(max_length=50)),
                ("Major", models.CharField(max_length=50)),
                ("Resume", models.FileField(upload_to="resumes/")),
            ],
        ),
    ]
