# Generated by Django 4.2.2 on 2023-10-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumebookapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentinfo",
            name="Tnumber",
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
