# Generated by Django 4.2.2 on 2023-10-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RecruiterLog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruiter",
            name="is_recruiter",
            field=models.BooleanField(default=True),
        ),
    ]
