# Generated by Django 4.2.2 on 2023-10-13 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "homepage",
            "0002_alter_customuser_options_alter_customuser_managers_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelManagers(name="customuser", managers=[],),
    ]
