# Generated by Django 4.2.2 on 2023-10-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0003_alter_customuser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="has_submitted_info",
            field=models.BooleanField(default=False),
        ),
    ]
